### ISSUE TITLE
Implements timeout on rabbitmq connection by default

### ISSUE THREAD

**Issue by Duarterix** [alykamb/nestjs-queuebus#1]
Hello my friend, 

From time to time we need to restart the rabbit pod due to the number of connections. It doesn't clean up and ends up filling up the RAM of the pods in Kubernetes.

![image](https://github.com/alykamb/nestjs-queuebus/assets/49329842/2ba21415-2d2f-4064-9ac8-0ad4947fdace)

Through some research I realized that there are people with the same problem and to solve it they added a timeout to the connection.

https://stackoverflow.com/questions/12499174/rabbitmq-c-sharp-driver-stops-receiving-messages/12735286#12735286

Maybe this not the better approach although be likely to solve the issue

https://github.com/alykamb/nestjs-queuebus/blob/d2ce196d80e3bad10170c590b98aab5cc782c1e1/src/transports/rabbitMq/rabbitMq.ts#L100

Great thanks :)

**Comment by Duarterix** [comment]
You can grant a contributor on this project to fix it

https://amqp-node.github.io/amqplib/channel_api.html#connect

![image](https://github.com/alykamb/nestjs-queuebus/assets/49329842/f1727b50-0ae0-428a-b827-d222306e599b)

**Comment by alykamb** [comment]
you can pass a heartbeat config now: https://github.com/alykamb/nestjs-queuebus/commit/ce06e25a9f23edac082cc3629ef8511addeccfd

BTW, this was already possible by extending the RabbitMQ class and overriding the getConsumer method

I hope the fix helps you.

Fell free to create PRs as well.
